/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

/**
 *
 * @author HP
 */
public class FinanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FinanceJPanel
     */
    public FinanceJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTuitionPayment = new javax.swing.JLabel();
        lblCurrentBalance = new javax.swing.JLabel();
        lblPaymentAmount = new javax.swing.JLabel();
        fieldPaymentAmount = new javax.swing.JTextField();
        lblPaymentHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaymentHistory = new javax.swing.JTable();
        btnPayFullBalance = new javax.swing.JButton();
        btnPayAmount = new javax.swing.JButton();
        btnRefund = new javax.swing.JButton();

        lblTuitionPayment.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTuitionPayment.setText("Tuition Payment");

        lblCurrentBalance.setText("Current Balance: $");

        lblPaymentAmount.setText("Payment Amount:");

        lblPaymentHistory.setText("Payment History");

        tblPaymentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Amount Paid", "Balance After", "Method"
            }
        ));
        jScrollPane1.setViewportView(tblPaymentHistory);

        btnPayFullBalance.setText("Pay Full Balance");

        btnPayAmount.setText("Pay Amount");

        btnRefund.setText("Refund");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTuitionPayment)
                    .addComponent(lblCurrentBalance)
                    .addComponent(lblPaymentHistory)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPaymentAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPayFullBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefund, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTuitionPayment)
                .addGap(18, 18, 18)
                .addComponent(lblCurrentBalance)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPaymentAmount)
                    .addComponent(fieldPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayFullBalance)
                    .addComponent(btnPayAmount)
                    .addComponent(btnRefund))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblPaymentHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayAmount;
    private javax.swing.JButton btnPayFullBalance;
    private javax.swing.JButton btnRefund;
    private javax.swing.JTextField fieldPaymentAmount;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurrentBalance;
    private javax.swing.JLabel lblPaymentAmount;
    private javax.swing.JLabel lblPaymentHistory;
    private javax.swing.JLabel lblTuitionPayment;
    private javax.swing.JTable tblPaymentHistory;
    // End of variables declaration//GEN-END:variables
}
