/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;
import Business.Business;
import Business.Profiles.StudentProfile;
import Bussiness.Finance.TuitionDirectory;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Bussiness.Finance.TuitionDirectory.Payment; // ✅ Add this import
import java.util.List;                              // ✅ Add this import



/**
 *
 * @author HP
 */
public class FinanceJPanel extends javax.swing.JPanel {
     
    private Business business;
    private StudentProfile student;
    private TuitionDirectory tuitionDirectory;
    private DecimalFormat df = new DecimalFormat("#,##0.00");
    private JPanel cardPanel; // ✅ Added this line


    /**
     * Creates new form FinanceJPanel
     */
   public FinanceJPanel(Business business, StudentProfile student, JPanel cardPanel) {
    initComponents();
    this.business = business;
    this.student = student;
    this.cardPanel = cardPanel; // ✅ Store reference
    this.tuitionDirectory = business.getTuitionDirectory();
    tuitionDirectory.initializeStudentAccount(student);

    updateCurrentBalance();
    populatePaymentHistory();
}


    // ✅ Updates the Current Balance label
private void updateCurrentBalance() {
    double balance = tuitionDirectory.getTotalTuitionForStudent(student);
    lblCurrentBalance.setText("Current Balance: $" + df.format(balance));
}
// ✅ Populates the payment history table (optional demo or data-driven)



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTuitionPayment = new javax.swing.JLabel();
        lblCurrentBalance = new javax.swing.JLabel();
        lblPaymentAmount = new javax.swing.JLabel();
        fieldPaymentAmount = new javax.swing.JTextField();
        lblPaymentHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaymentHistory = new javax.swing.JTable();
        btnPayFullBalance = new javax.swing.JButton();
        btnPayAmount = new javax.swing.JButton();
        btnRefund = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblTuitionPayment.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTuitionPayment.setText("Tuition Payment");

        lblCurrentBalance.setText("Current Balance: $");

        lblPaymentAmount.setText("Payment Amount:");

        fieldPaymentAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPaymentAmountActionPerformed(evt);
            }
        });

        lblPaymentHistory.setText("Payment History");

        tblPaymentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Amount Paid", "Balance After", "Method"
            }
        ));
        jScrollPane1.setViewportView(tblPaymentHistory);

        btnPayFullBalance.setText("Pay Full Balance");
        btnPayFullBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayFullBalanceActionPerformed(evt);
            }
        });

        btnPayAmount.setText("Pay Amount");
        btnPayAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayAmountActionPerformed(evt);
            }
        });

        btnRefund.setText("Refund");
        btnRefund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefundActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurrentBalance)
                    .addComponent(lblPaymentHistory)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPaymentAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPayFullBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefund, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTuitionPayment)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTuitionPayment)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(lblCurrentBalance)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPaymentAmount)
                    .addComponent(fieldPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayFullBalance)
                    .addComponent(btnPayAmount)
                    .addComponent(btnRefund))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblPaymentHistory)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayFullBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayFullBalanceActionPerformed
        // TODO add your handling code here:
       double balance = tuitionDirectory.getTotalTuitionForStudent(student);
    if (balance <= 0) {
        JOptionPane.showMessageDialog(this, "No outstanding balance to pay.");
        return;
    }

    tuitionDirectory.recordPayment(student, balance, "Full Balance Payment");
    JOptionPane.showMessageDialog(this, "Full balance of $" + df.format(balance) + " paid successfully!");

    updateCurrentBalance();
    populatePaymentHistory();
    }//GEN-LAST:event_btnPayFullBalanceActionPerformed

    private void btnPayAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayAmountActionPerformed
        // TODO add your handling code here:
                                               
    try {
        double amount = Double.parseDouble(fieldPaymentAmount.getText().trim());
        if (amount <= 0) {
            JOptionPane.showMessageDialog(this, "Enter a valid positive payment amount.");
            return;
        }

        double currentBalance = tuitionDirectory.getTotalTuitionForStudent(student);
        if (amount > currentBalance) {
            JOptionPane.showMessageDialog(this, "Payment exceeds current balance!");
            return;
        }

        // Process payment (you can expand this logic in TuitionDirectory)
        tuitionDirectory.recordPayment(student, amount, "Manual Payment");
        JOptionPane.showMessageDialog(this, "Payment of $" + df.format(amount) + " successful!");

        updateCurrentBalance();
        populatePaymentHistory();
        fieldPaymentAmount.setText("");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid amount.");
    }
  

    }//GEN-LAST:event_btnPayAmountActionPerformed

    private void btnRefundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefundActionPerformed
        // TODO add your handling code here:
    double refundAmount = 500.00; // Example fixed refund
    tuitionDirectory.refundTuition(student, refundAmount);
    JOptionPane.showMessageDialog(this, "Refund of $" + df.format(refundAmount) + " processed successfully!");

    updateCurrentBalance();
    populatePaymentHistory();
    }//GEN-LAST:event_btnRefundActionPerformed

    private void fieldPaymentAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPaymentAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPaymentAmountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    cardPanel.remove(this); // remove current FinanceJPanel
    CardLayout layout = (CardLayout) cardPanel.getLayout();
    layout.previous(cardPanel); // show previous panel (StudentWorkAreaJPanel)
    }//GEN-LAST:event_btnBackActionPerformed
    
    // ✅ Dynamically load payment and refund history for the student
    private void populatePaymentHistory() {
    DefaultTableModel model = (DefaultTableModel) tblPaymentHistory.getModel();
    model.setRowCount(0); // clear table

    try {
        List<Payment> paymentList = tuitionDirectory.getPaymentsForStudent(student);
        if (paymentList == null || paymentList.isEmpty()) {
            model.addRow(new Object[]{"No transactions yet", "-", "-", "-"});
            return;
        }

        for (Payment p : paymentList) {
            String sign = p.getAmount() < 0 ? "Refund" : "Payment";
            model.addRow(new Object[]{
                p.getDate(),
                (p.getAmount() < 0 ? "-$" : "$") + df.format(Math.abs(p.getAmount())),
                "$" + df.format(p.getBalanceAfter()),
                sign + " (" + p.getMethod() + ")"
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading payment history: " + e.getMessage());
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPayAmount;
    private javax.swing.JButton btnPayFullBalance;
    private javax.swing.JButton btnRefund;
    private javax.swing.JTextField fieldPaymentAmount;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurrentBalance;
    private javax.swing.JLabel lblPaymentAmount;
    private javax.swing.JLabel lblPaymentHistory;
    private javax.swing.JLabel lblTuitionPayment;
    private javax.swing.JTable tblPaymentHistory;
    // End of variables declaration//GEN-END:variables
}
