/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

/**
 *
 * @author HP
 */
public class GraduationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GraduationJPanel
     */
    public GraduationJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGraduationAudit = new javax.swing.JLabel();
        lblTotalCreditsRequired = new javax.swing.JLabel();
        lblCreditsCompleted = new javax.swing.JLabel();
        lblCreditsRemaining = new javax.swing.JLabel();
        lblProgress = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        lblCoreCourseRequirement = new javax.swing.JLabel();
        lblElectiveCredits = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGraduationAudit = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        lblCompletedCredits = new javax.swing.JLabel();
        lblNeededCredits = new javax.swing.JLabel();

        lblGraduationAudit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGraduationAudit.setText("Graduation Requirements Audit - MSIS Program");

        lblTotalCreditsRequired.setText("Total Credits Required:");

        lblCreditsCompleted.setText("Credits Completed:");

        lblCreditsRemaining.setText("Credits Remaining:");

        lblProgress.setText("Progress:");

        lblCoreCourseRequirement.setText("Core Course Requirement:");

        lblElectiveCredits.setText("Elective Credits:                                           ");

        tblGraduationAudit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Code", "Course Name", "Credits", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblGraduationAudit);

        lblStatus.setText(" Status:       ");

        lblCompletedCredits.setText("Completed:   ");

        lblNeededCredits.setText("Needed: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGraduationAudit)
                            .addComponent(lblTotalCreditsRequired)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProgress)
                                .addGap(18, 18, 18)
                                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCreditsCompleted)
                            .addComponent(lblCreditsRemaining)
                            .addComponent(lblCoreCourseRequirement)
                            .addComponent(lblElectiveCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCompletedCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNeededCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 108, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblGraduationAudit)
                .addGap(18, 18, 18)
                .addComponent(lblTotalCreditsRequired)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCreditsCompleted)
                .addGap(16, 16, 16)
                .addComponent(lblCreditsRemaining)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProgress, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCoreCourseRequirement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblElectiveCredits)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCompletedCredits)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNeededCredits)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatus)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompletedCredits;
    private javax.swing.JLabel lblCoreCourseRequirement;
    private javax.swing.JLabel lblCreditsCompleted;
    private javax.swing.JLabel lblCreditsRemaining;
    private javax.swing.JLabel lblElectiveCredits;
    private javax.swing.JLabel lblGraduationAudit;
    private javax.swing.JLabel lblNeededCredits;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotalCreditsRequired;
    private javax.swing.JTable tblGraduationAudit;
    // End of variables declaration//GEN-END:variables
}
