/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.ProfileWorkAreaMainFrame;



/**
 *
 * @author HP
 */
public class ManageStudentProfileJPanel extends javax.swing.JPanel {
    private Business business;
    private StudentProfile student;
    private javax.swing.JFrame mainFrame;


    /**
     * Creates new form ManageStudentProfileJPanel
     */
    public ManageStudentProfileJPanel(Business business, StudentProfile student, javax.swing.JFrame mainFrame)
    {
    initComponents();
    this.business = business;
    this.student = student;
    this.mainFrame = mainFrame; // ✅ store reference to your main frame
    loadStudentDetails();
    setEditableFields(false);
     }


    private void loadStudentDetails() {
        if (student == null || student.getPerson() == null) {
            JOptionPane.showMessageDialog(this, "Student data not available.");
            return;
        }

        fieldStudentID.setText(student.getPerson().getPersonId());
        fieldFullName.setText(student.getPerson().getName());
        fieldEmailID.setText(student.getPerson().getEmail());
        fieldPhoneNumber.setText(student.getPerson().getPhoneNumber());
        fieldDepartment.setText(student.getDepartment() != null ? student.getDepartment() : "");
        fieldProgram.setText(student.getProgram() != null ? student.getProgram() : "");
    }
     private void setEditableFields(boolean editable) {
        fieldFullName.setEditable(editable);
        fieldEmailID.setEditable(editable);
        fieldPhoneNumber.setEditable(editable);
        fieldDepartment.setEditable(editable);
        fieldProgram.setEditable(editable);
    }

    // ======== Save Updated Data ========
    private void saveProfileUpdates() {
        if (student == null || student.getPerson() == null) return;

        String name = fieldFullName.getText().trim();
        String email = fieldEmailID.getText().trim();
        String phone = fieldPhoneNumber.getText().trim();
        String dept = fieldDepartment.getText().trim();
        String prog = fieldProgram.getText().trim();

        // Basic validation
        if (name.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Full Name and Email are required.");
            return;
        }

        // Update person details
        student.getPerson().setName(name);
        student.getPerson().setEmail(email);
        student.getPerson().setPhoneNumber(phone);
        student.setDepartment(dept);
        student.setProgram(prog);

        JOptionPane.showMessageDialog(this, "Profile updated successfully!");
        setEditableFields(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblStudentID = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldStudentID = new javax.swing.JTextField();
        fieldFullName = new javax.swing.JTextField();
        fieldEmailID = new javax.swing.JTextField();
        fieldPhoneNumber = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        fieldDepartment = new javax.swing.JTextField();
        lblProgram = new javax.swing.JLabel();
        fieldProgram = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("My Profile");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblStudentID.setText("Student ID");

        lblFullName.setText("Full Name");

        lblEmailID.setText("Email ID");

        jLabel6.setText("Phone Number");

        fieldStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStudentIDActionPerformed(evt);
            }
        });

        fieldFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFullNameActionPerformed(evt);
            }
        });

        fieldEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailIDActionPerformed(evt);
            }
        });

        fieldPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPhoneNumberActionPerformed(evt);
            }
        });

        lblDepartment.setText("Department");

        fieldDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDepartmentActionPerformed(evt);
            }
        });

        lblProgram.setText("Program");

        fieldProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldProgramActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(btnUpdate)
                .addGap(123, 123, 123)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailID)
                    .addComponent(lblFullName)
                    .addComponent(jLabel6)
                    .addComponent(lblDepartment)
                    .addComponent(lblStudentID)
                    .addComponent(lblProgram))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249))
                    .addComponent(fieldFullName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEmailID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldDepartment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldProgram, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnLogout))
                    .addComponent(jLabel1))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentID)
                    .addComponent(fieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullName)
                    .addComponent(fieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailID)
                    .addComponent(fieldEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(fieldDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgram)
                    .addComponent(fieldProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave))
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStudentIDActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         setEditableFields(true);
        JOptionPane.showMessageDialog(this, "Edit mode enabled. You can now update your profile.");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        saveProfileUpdates();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void fieldFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFullNameActionPerformed

    private void fieldEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailIDActionPerformed

    private void fieldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPhoneNumberActionPerformed

    private void fieldDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDepartmentActionPerformed

    private void fieldProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldProgramActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
     int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout Confirmation",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, "You have been logged out successfully.");

        // ✅ Dispose current student window or frame
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();

        // ✅ Reopen main login/home frame
        ProfileWorkAreaMainFrame mainFrame = new ProfileWorkAreaMainFrame();
        mainFrame.setVisible(true);
    }
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField fieldDepartment;
    private javax.swing.JTextField fieldEmailID;
    private javax.swing.JTextField fieldFullName;
    private javax.swing.JTextField fieldPhoneNumber;
    private javax.swing.JTextField fieldProgram;
    private javax.swing.JTextField fieldStudentID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblStudentID;
    // End of variables declaration//GEN-END:variables
}
