/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Profiles.Profile;
import Business.Profiles.StudentDirectory;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import Departments.Department;
import Global.GlobalFunctions;
import static Global.GlobalFunctions.randomNumber;
import Global.GlobalVariables;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class ManagePersonsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;

    public ManagePersonsJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        initializeCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbDepartment = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblDept = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbPersonType1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(20, 400, 74, 23);

        Next.setText("Next >>");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        add(Next);
        Next.setBounds(500, 400, 80, 23);

        jLabel1.setText("Name");
        add(jLabel1);
        jLabel1.setBounds(180, 70, 50, 16);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Personnel (HR)");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister);
        btnRegister.setBounds(270, 400, 100, 23);

        jLabel3.setText("Email");
        add(jLabel3);
        jLabel3.setBounds(180, 110, 37, 16);
        add(txtName);
        txtName.setBounds(270, 70, 160, 22);
        add(txtEmail);
        txtEmail.setBounds(270, 110, 150, 22);

        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbDepartment);
        cmbDepartment.setBounds(270, 160, 150, 22);

        jLabel4.setText("Role");
        add(jLabel4);
        jLabel4.setBounds(190, 210, 37, 16);

        lblUsername.setText("Username");
        add(lblUsername);
        lblUsername.setBounds(170, 280, 60, 16);

        lblPassword.setText("Password");
        add(lblPassword);
        lblPassword.setBounds(170, 330, 60, 16);
        add(txtUserName);
        txtUserName.setBounds(270, 280, 160, 22);
        add(txtPassword);
        txtPassword.setBounds(270, 330, 160, 22);

        lblDept.setText("Department");
        add(lblDept);
        lblDept.setBounds(170, 160, 70, 16);

        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });
        add(txtContact);
        txtContact.setBounds(270, 240, 160, 22);

        jLabel5.setText("Contact no");
        add(jLabel5);
        jLabel5.setBounds(170, 240, 60, 16);

        cmbPersonType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPersonType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPersonType1ActionPerformed(evt);
            }
        });
        add(cmbPersonType1);
        cmbPersonType1.setBounds(270, 200, 150, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");

    }//GEN-LAST:event_BackActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:

        AdministerPersonJPanel mppd = new AdministerPersonJPanel(business, CardSequencePanel);
        CardSequencePanel.add(mppd);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_NextActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        int id = GlobalFunctions.randomNumber();
        PersonDirectory persondirectory = business.getPersonDirectory();
        int randomId = randomNumber();

        if (validatePerson(txtEmail.getText())) {

            Person person001 = persondirectory.newPerson(String.valueOf(randomId),
                    txtName.getText(), txtEmail.getText());
            person001.setContactInfo(txtContact.getText());

            String type = (String) cmbPersonType1.getSelectedItem();
            Profile profile = null;
                            System.out.println("lets start registration " + type);

            if (type.equals("STUDENT")) {
                System.out.println("STUDENT ENROLLMENT");
                StudentDirectory studentdirectory = business.getStudentDirectory();
                profile = studentdirectory.newStudentProfile(person001);
                profile.setDepartment(business.
                        getDepartmentDictonary().getDepartmentByName((String)cmbDepartment.getSelectedItem()));
            } else if (type.equals("FACULTY")) {
                // TODO: Add code for faculty
            }

// Create User accounts that link to specific profiles
            UserAccountDirectory uadirectory = business.getUserAccountDirectory();
            UserAccount ua3 = uadirectory.newUserAccount(profile, txtUserName.getText(),
                    txtPassword.getText());

            // Success message
            JOptionPane.showMessageDialog(this, "Account successfully created with university id: " + randomId, "Information",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        clearFields();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void cmbPersonType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPersonType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPersonType1ActionPerformed

    private void clearFields() {
        // Reset text fields
        txtName.setText("");
        txtEmail.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
    }

    private void initializeCombo() {
        cmbDepartment.removeAllItems();
        cmbPersonType1.removeAllItems();

        for (String type : GlobalVariables.PERSONA_TYPE) {
            cmbPersonType1.addItem(type);
        }

        for (Department dept : business.getDepartmentDictonary().getDepartments()) {
            cmbDepartment.addItem(dept.getName());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Next;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JComboBox<String> cmbPersonType1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDept;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private boolean validatePerson(String email) {

        PersonDirectory persondirectory = business.getPersonDirectory();

        if (persondirectory.findPersonByEmailId(email) == null) {
            return true;
        }

        clearFields();
        JOptionPane.showMessageDialog(this, "Account already exist please use different email id: ", "Error",
                JOptionPane.INFORMATION_MESSAGE);
        return false;
    }

}
